name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          runVcpkgInstall: true
          vcpkgJsonGlob: vcpkg.json
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'

      - name: Show the tree
        run: cmd tree
        
      - name: ls vcpkg
        run: | 
            cmd dir D:\a\ffmpeg\b\vcpkg\
            cmd dir D:\a\ffmpeg\b\vcpkg\vcpkg
            cmd dir D:\a\ffmpeg\b\vcpkg\vcpkg\packages
            cmd dir D:\a\ffmpeg\b\vcpkg\vcpkg\ffmpeg_x64-windows
            
