name: CI

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        platform: [x86-windows, x64-windows]
        version: [6.1.1.6]
        
    env:
        VCPKG_DEFAULT_TRIPLET: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          runVcpkgInstall: true
          vcpkgJsonGlob: vcpkg.json
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'

      - uses: vimtor/action-zip@v1.2
        with:
          files: ./969f6665-88a2-4c98-938e-ca9259871fec/vcpkg_installed/${{ matrix.platform }}/
          dest: ffmpeg-${{ matrix.version }}-${{ matrix.platform}}.zip
          recursive: true
          
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "ffmpeg-${{ matrix.version }}-${{ matrix.platform}}.zip"
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
          tag: "${{ matrix.version }}.${{ matrix.platform }}"
        
