name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          runVcpkgInstall: true
          vcpkgJsonGlob: vcpkg.json
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'

      - name: Show the tree
        run: tree
          
      - name: Affichage path current
        run: dir .\969f6665-88a2-4c98-938e-ca9259871fec
          
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'release.zip'
          path: '.\969f6665-88a2-4c98-938e-ca9259871fec\vcpkg_installed\x64-windows'
                    
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: ${{ secrets.DOWNLOAD_RELEASE_TOKEN }}